# Generated by Django 2.1.5 on 2020-06-02 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('davinci', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='REGISTER_MODEL',
        ),
    ]
