# Generated by Django 2.1.5 on 2020-06-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('davinci', '0002_delete_register_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='USER_DATA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=264)),
            ],
        ),
    ]
