# Generated by Django 2.1.5 on 2020-06-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('davinci', '0004_user_data_login_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='country_code',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='user_data',
            name='first_name',
            field=models.CharField(blank=True, max_length=264),
        ),
        migrations.AddField(
            model_name='user_data',
            name='last_name',
            field=models.CharField(blank=True, max_length=264),
        ),
        migrations.AddField(
            model_name='user_data',
            name='mobile_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
