# Generated by Django 2.1.5 on 2020-06-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('davinci', '0005_auto_20200603_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='first_name',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='last_name',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
    ]
