# Generated by Django 2.1.5 on 2020-06-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('davinci', '0006_auto_20200603_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='folder_files_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=264)),
                ('folder_count', models.PositiveIntegerField(null=True)),
                ('files_count', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
