# Generated by Django 2.1.5 on 2020-06-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('davinci', '0008_auto_20200607_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder_files_model',
            name='username',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='username',
            field=models.CharField(max_length=264),
        ),
    ]
